sudo: false

dist: xenial

language:
  - python

matrix:
  include:
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
  allow_failures:
    # Tox will fail right now. Make the change, and re-enable this
    - env: TOXENV=flake8

cache:
  directories:
    - $(HOME)/.cache/pip
    - $(TRAVIS_BUILD_DIR)/.tox

install:
  - pip install tox

script:
  - tox


notifications:
  email:
    on_failure: always
    on_success: change
